version: '3.1'
services:
  postgres-db:
    container_name: 'postgres-db'
    image: postgres:alpine
    ports:
    - '5432:5432'
    environment:
    - POSTGRES_DB=localbyadb
    - POSTGRES_USER=localbyauser
    - POSTGRES_PASSWORD=password